---
- name: XFCE environment setup
  tags: xfce-setup
  hosts: all
  tasks:
  - name: XFCE set taskbar title
    command: /usr/bin/xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-title -s "CrewOS" 
  
  - name: XFCE set wallpaper
    command: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path --set /usr/share/backgrounds/xfce/crewos-wallpaper.jpg
  
  - name: XFCE set wallpaper last image
    command: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image --set /usr/share/backgrounds/xfce/crewos-wallpaper.jpg