---
- name: XFCE environment setup
  tags: xfce-setup
  hosts: all
  tasks:
  - name: XFCE set taskbar title
    command: /usr/bin/xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-title -s "CrewOS" --create -t string
  
  - name: XFCE set wallpaper
    command: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path --set /usr/share/backgrounds/xfce/crewos-wallpaper.jpg
  
  - name: XFCE set wallpaper last image
    command: xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image --set /usr/share/backgrounds/xfce/crewos-wallpaper.jpg
  
  - name: XFCE set taskbar icon
    command: /usr/bin/xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-icon -s "/usr/share/icons/fire.png" --create -t string
  
  - name: XFCE set lockscreen Background
    become: yes
    copy:
      src: lightdm-gtk-greeter.conf
      dest: /etc/lightdm/lightdm-gtk-greeter.conf

- name: XFCE Menu
  tags: xfce-menu
  hosts: all
  tasks:
  - name: Setup menu
    become: yes
    copy: 
      src: menu/xfce-applications.menu
      dest: /etc/xdg/menus/

  - name: Setup menu directories
    become: yes
    copy:
      src: "{{ item }}"
      dest: /usr/share/desktop-directories/
    
    with_fileglob:
      - menu/crew-*.directory

  - name: Setup menu shortcuts
    become: yes
    copy:
      src: "{{ item }}"
      dest: /usr/share/applications/
    
    with_fileglob:
      - menu/shortcuts/crew*.desktop
    
