---
- name: Install Java
  tags: java
  hosts: all
  tasks:
  - name: Install JRE
    become: yes
    apt:
      pkg:
      - default-jre

- name: Install Ruby
  tags: ruby
  hosts: all
  tasks:
  - name: Install Ruby
    become: yes
    apt:
      pkg:
      - ruby

- name: Install Golang
  tags: golang
  hosts: all
  vars:
    golang_ver: 1.16
  tasks:
  - name: Download and Extract Golang
    shell: |
      wget "https://dl.google.com/go/go{{ golang_ver }}.linux-amd64.tar.gz"
      tar -xvf "go{{ golang_ver }}.linux-amd64.tar.gz"
      rm -rf "go{{ golang_ver }}.linux-amd64.tar.gz"
  
  - name: Setup Golang Environment
    become: yes
    command: mv go /usr/local

  - name: Setup Environment Variables
    shell: |
      echo 'export GOROOT=/usr/local/go' >> ~/.bash_profile
      echo 'export GOPATH=$HOME/go'	>> ~/.bash_profile			
      echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.bash_profile	