---
- name: Install Java
  tags: java
  hosts: all
  tasks:
  - name: Install JRE
    become: yes
    apt:
      pkg:
      - default-jre

- name: Install Golang
  tags: golang
  hosts: all
  vars:
    golang_ver: 1.13.4
  tasks:
  - name: Download and Extract Golang
    become: yes
    shell: |
      wget "https://dl.google.com/go/go{{ golang_ver }}.linux-amd64.tar.gz"
      tar -xvf "go{{ golang_ver }}.linux-amd64.tar.gz"
      mv go /usr/local
      rm -r "go{{ golang_ver }}.linux-amd64.tar.gz"
  
  - name: Set Golang Environment
    shell: |
      echo 'export GOROOT=/usr/local/go' >> ~/.bash_profile
      echo 'export GOPATH=$HOME/go'	>> ~/.bash_profile			
      echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> ~/.bash_profile	