# ---
# - name: Set proper permissions and ownerships
#   hosts: all
#   tasks:
#   - name: Change ownership of crew related files
#     file:
#       path: /opt/crew
#       state: directory
#       recurse: yes
#       owner: crew
#       group: crew