---
- name: Provision Operating System Necessities
  hosts: all
  tasks:
  - name: Update APT cache
    become: yes
    apt:
      update_cache: yes

  - name: Install Web Utilities
    become: yes
    apt:
      pkg:
      - curl
      - wget
      - git
      - netcat

  - name: Install Dependencies
    become: yes
    apt:
      pkg:
      - libcurl4-openssl-dev 
      - libssl-dev
      - libpcap-dev

  - name: Install Python Utilities
    become: yes
    apt:
      pkg:
      - python3-pip
      - python-dnspython
  
  - name: Install Productivity Utilities
    become: yes
    apt:
      pkg:
      - vim
      - jq

- name: Configure Operating System Environment
  tags: os-setup
  hosts: all
  tasks:
  - name: Create CrewOS Folder
    become: yes
    file: 
      path: /opt/crew
      state: directory
      owner: crew
      group: crew

  - name: Create CrewOS subfolder for enum 
    become: yes
    file: 
      path: /opt/crew/enum
      state: directory
      owner: crew
      group: crew

  - name: Create CrewOS subfolder for fuzzers 
    become: yes
    file: 
      path: /opt/crew/fuzzers
      state: directory
      owner: crew
      group: crew

  
  - name: Create CrewOS subfolder for proxies 
    become: yes
    file: 
      path: /opt/crew/proxies
      state: directory
      owner: crew
      group: crew

  
  - name: Create CrewOS subfolder for recon 
    become: yes
    file: 
      path: /opt/crew/recon
      state: directory
      owner: crew
      group: crew

  
  - name: Create CrewOS subfolder for scanners
    become: yes
    file: 
      path: /opt/crew/scanners
      state: directory
      owner: crew
      group: crew
 
  - name: Create CrewOS subfolder for miscellaneous
    become: yes
    file: 
      path: /opt/crew/misc
      state: directory
      owner: crew
      group: crew

  - name: Create CrewOS subfolder for takover tools
    become: yes
    file: 
      path: /opt/crew/takeovers
      state: directory
      owner: crew
      group: crew
  
  - name: Create CrewOS subfolder for wordlists
    become: yes
    file: 
      path: /opt/crew/wordlists
      state: directory
      owner: crew
      group: crew