---
- name: Prepare Operating System
  hosts: all
  tasks:
  - name: Create CrewOS Folders
    become: yes
    shell: |
      mkdir /opt/crew
      mkdir /opt/crew/enum
      mkdir /opt/crew/fuzzers
      mkdir /opt/crew/proxies
      mkdir /opt/crew/recon
      mkdir /opt/crew/scanners
 
  - name: Copy Wallpaper
    become: yes
    copy:
      src: wallpaper.jpg
      dest: /usr/share/backgrounds/xfce/crewos-wallpaper.jpg
 
  - name: Update APT cache
    become: yes
    apt:
      update_cache: yes

  - name: Install Web Utilities
    become: yes
    apt:
      pkg:
      - curl
      - wget
      - git

  - name: Install Python Utilities
    become: yes
    apt:
      pkg:
      - python3-pip
      - python-pip
  
  - name: Install Productivity Utilities
    become: yes
    apt:
      pkg:
      - terminator
      - gedit
      - vim

