---
- name: Setup Operating System
  tags: os-setup
  hosts: all
  vars_files:
    - vars/version.yml
  tasks:
  - name: Setup os-release
    become: yes
    copy:
      content: |
        PRETTY_NAME="CrewOS {{ crew_version }}"
        NAME="CrewOS"
        VERSION_ID="{{ crew_version }}"
        VERSION="{{ crew_version }}"
        CODENAME="{{ crew_version }}"
        ID=crewos
        ID_LIKE=debian
        HOME_URL="https://crewlinux.org/"
        SUPPORT_URL="https://crewlinux.org/support"
        BUG_REPORT_URL="https://crewlinux.org/report"
      dest: /etc/os-release
 
  - name: Setup message of the day
    become: yes
    copy:
      content: |
        The programs included with the Debian GNU/Linux system are free software;
        the exact distribution terms for each program are described in the
        individual files in /usr/share/doc/*/copyright.

        Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
        permitted by applicable law.  

        Welcome to CrewOS!
      dest: /etc/motd