---
- name: Provision Operating System Necessities
  hosts: all
  tasks:
  - name: Add crew user
    tags: user-create
    become: yes
    user:
      name: crew
      shell: /bin/bash
      groups: sudo
      append: yes
      password: $1$$BA5bqnCvtLxzPpKvWkkPX. # crew

  - name: Copy Wallpaper
    become: yes
    copy:
      src: wallpaper.jpg
      dest: /usr/share/backgrounds/xfce/crewos-wallpaper.jpg
 
  - name: Update APT cache
    become: yes
    apt:
      update_cache: yes

  - name: Install Web Utilities
    become: yes
    apt:
      pkg:
      - curl
      - wget
      - git

  - name: Install Dependencies
    become: yes
    apt:
      pkg:
      - libcurl4-openssl-dev 
      - libssl-dev

  - name: Install Python Utilities
    become: yes
    apt:
      pkg:
      - python3-pip
      - python-pip
  
  - name: Install Productivity Utilities
    become: yes
    apt:
      pkg:
      - terminator
      - gedit
      - vim
      - jq

- name: Configure Operating System Environment
  tags: os-setup
  hosts: all
  vars_files:
    - vars/version.yml
    - vars/links.yml
  tasks:
  - name: Setup os-release
    become: yes
    copy:
      content: |
        PRETTY_NAME="CrewOS {{ crew_version }}"
        NAME="CrewOS"
        VERSION_ID="{{ crew_version }}"
        VERSION="{{ crew_version }}"
        CODENAME="{{ crew_version }}"
        ID=crewos
        ID_LIKE=debian
        HOME_URL="https://{{ crew_site }}/"
        SUPPORT_URL="https://{{ crew_site }}/support"
        BUG_REPORT_URL="https://{{ crew_site }}/report"
      dest: /etc/os-release
 
  - name: Setup message of the day
    become: yes
    copy:
      content: |
        The programs included with the Debian GNU/Linux system are free software;
        the exact distribution terms for each program are described in the
        individual files in /usr/share/doc/*/copyright.

        Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
        permitted by applicable law.  

        Welcome to CrewOS!

        Check out our website for future announcements.
        https://{{crew_site}}
      dest: /etc/motd
  
  - name: Create CrewOS Folder
    become: yes
    file: 
      path: /opt/crew
      state: directory
      owner: crew
      group: crew

  - name: Create CrewOS subfolder for enum 
    become: yes
    file: 
      path: /opt/crew/enum
      state: directory
      owner: crew
      group: crew

  - name: Create CrewOS subfolder for fuzzers 
    become: yes
    file: 
      path: /opt/crew/fuzzers
      state: directory
      owner: crew
      group: crew

  
  - name: Create CrewOS subfolder for proxies 
    become: yes
    file: 
      path: /opt/crew/proxies
      state: directory
      owner: crew
      group: crew

  
  - name: Create CrewOS subfolder for recon 
    become: yes
    file: 
      path: /opt/crew/recon
      state: directory
      owner: crew
      group: crew

  
  - name: Create CrewOS subfolder for scanners
    become: yes
    file: 
      path: /opt/crew/scanners
      state: directory
      owner: crew
      group: crew
 