---
- name: Install Knockpy
  tags: knockpy
  hosts: all
  tasks:
  - name: Download Knockpy
    command: git clone https://github.com/guelfoweb/knock.git
  
  - name: Install Knockpy
    become: yes
    shell: |
      cd knock
      python setup.py install
      rm -rf knock

  - name: Remove Knockpy
    become: yes
    command: rm -rf knock

- name: Install Sublist3r
  tags: sublist3r
  hosts: all
  tasks:
  - name: Download Sublist3r
    become: yes
    command: git clone https://github.com/aboul3la/Sublist3r.git
      
  - name: Install Sublist3r
    become: yes
    shell: |
      cd Sublist3r
      python3 setup.py install

  - name: Remove Sublist3r
    become: yes
    command: rm -rf Sublist3r

- name: Install unfurl
  tags: unfurl
  hosts: all
  tasks:
  - name: Download unfurl
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/unfurl

  - name: Setup unfurl
    shell: |
      mkdir /opt/crew/enum/unfurl
      mv go/bin/unfurl /opt/crew/enum/unfurl/

  - name: Symink unfurl
    become: yes
    file:
      src: /opt/crew/enum/unfurl/unfurl
      dest: /usr/local/bin/unfurl
      state: link

- name: Install httprobe
  tags: httprobe
  hosts: all
  tasks:
  - name: Download and install httprobe
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/httprobe 

  - name: Setup httprobe
    shell: |
      mkdir /opt/crew/enum/httprobe
      mv go/bin/httprobe /opt/crew/enum/httprobe/

  - name: Symink httprobe
    become: yes
    file:
      src: /opt/crew/enum/httprobe/httprobe
      dest: /usr/local/bin/httprobe
      state: link

- name: Install dnsrecon
  tags: dnsrecon
  hosts: all
  tasks: 
  - name: Download dnsrecon
    command: git clone https://github.com/darkoperator/dnsrecon.git
  
  - name: Install dnsrecon
    become: yes
    command: pip3 install -r dnsrecon/requirements.txt

  - name: Setup dnsrecon
    command: mv dnsrecon /opt/crew/enum/
  
  - name: Setup dnsrecon script
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/enum/dnsrecon/dnsrecon.py "$@"

      dest:
        /usr/local/bin/dnsrecon
  
  - name: Setup dnsrecon as executable
    become: yes
    file: dest=/usr/local/bin/dnsrecon mode=a+x
  
  - name: Delete dnsrecon
    command: rm -rf dnsrecon

- name: Install subbrute
  tags: subbrute
  hosts: all
  tasks:
  - name: Download subbrute
    command: git clone https://github.com/TheRook/subbrute.git
  
  - name: Install subbrute
    shell: |
      mv subbrute /opt/crew/enum/
  
  - name: Setup subbrute script
    become: yes
    copy:
      content: |
        #!/bin/bash
        python3 /opt/crew/enum/subbrute/subbrute.py "$@"

      dest:
        /usr/local/bin/subbrute
  
  - name: Setup subbrute as executable
    become: yes
    file: dest=/usr/local/bin/subbrute mode=a+x
  
  - name: Delete subbrute
    command: rm -rf subbrute