---
- name: Install Knockpy
  tags: knockpy
  hosts: all
  tasks:
  - name: Download and install Knockpy
    become: yes
    shell: |
      apt install python-dnspython
      git clone https://github.com/guelfoweb/knock.git
      cd knock
      python setup.py install

- name: Install Sublist3r
  tags: sublister
  hosts: all
  tasks:
  - name: Download and install Sublist3r
    become: yes
    shell: |
      git clone https://github.com/aboul3la/Sublist3r.git
      cd Sublist3r
      python3 setup.py install

- name: Install unfurl
  tags: unfurl
  hosts: all
  tasks:
  - name: Download unfurl
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/unfurl

  - name: Setup unfurl
    become: yes
    shell: |
      mv go/bin/unfurl /usr/local/bin/


- name: Install httprobe
  tags: httprobe
  hosts: all
  tasks:
  - name: Download and install httprobe
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/httprobe 
  
  - name: Setup httprobe
    become: yes
    shell: |
      mv go/bin/httprobe /usr/local/bin/httprobe