---
- name: Install dirsearch
  hosts: all
  tasks:
  - name: Download dirsearch
    become: yes
    shell: |
      git clone https://github.com/maurosoria/dirsearch.git
      mv dirsearch /opt/fuzzers

  - name: Symlink dirsearch
    become: yes
    file:
      src: /opt/crew/fuzzers/dirsearch/dirsearch.py
      dest: /usr/local/bin/dirsearch  
      state: link

- name: Install Dirbuster
  hosts: all
  tasks:
  - name: Install dirbuster
    become: yes
    apt:
      pkg:
      - dirb

- name: Install sqlmap
  tags: sqlmap
  hosts: all
  tasks:
  - name: Download sqlmap
    become: yes
    shell: |
      git clone https://github.com/sqlmapproject/sqlmap.git /opt/crew/fuzzers/sqlmap/

  - name: Setup sqlmap
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/fuzzers/sqlmap/sqlmap.py

      dest:
        /usr/local/bin/sqlmap

  - name: Setup sqlmap as executable
    become: yes
    file: dest=/usr/local/bin/sqlmap mode=a+x
      
