---
- name: Install dirsearch
  hosts: all
  tasks:
  - name: Download dirsearch
    become: yes
    shell: |
      git clone https://github.com/maurosoria/dirsearch.git
      mv dirsearch /opt/fuzzers

  - name: Symlink dirsearch
    become: yes
    file:
      src: /opt/crew/fuzzers/dirsearch/dirsearch.py
      dest: /usr/local/bin/dirsearch  
      state: link
