---
- name: Install dirsearch
  hosts: all
  tasks:
  - name: Download dirsearch
    become: yes
    shell: |
      git clone https://github.com/maurosoria/dirsearch.git
      mv dirsearch /opt/fuzzers

  - name: Symlink dirsearch
    become: yes
    file:
      src: /opt/crew/fuzzers/dirsearch/dirsearch.py
      dest: /usr/local/bin/dirsearch  
      state: link

- name: Install Dirbuster
  hosts: all
  tasks:
  - name: Install dirbuster
    become: yes
    apt:
      pkg:
      - dirb

- name: Install sqlmap
  tags: sqlmap
  hosts: all
  tasks:
  - name: Download sqlmap
    become: yes
    shell: |
      git clone https://github.com/sqlmapproject/sqlmap.git /opt/crew/fuzzers/sqlmap/

  - name: Setup sqlmap
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/fuzzers/sqlmap/sqlmap.py

      dest:
        /usr/local/bin/sqlmap

  - name: Setup sqlmap as executable
    become: yes
    file: dest=/usr/local/bin/sqlmap mode=a+x
      
- name: Install FFuF
  tags: ffuf
  hosts: all
  tasks:
  - name: Download ffuf
    shell: |
      /usr/local/go/bin/go get -u github.com/ffuf/ffuf

  - name: Setup ffuf
    become: yes
    shell: |
      mv go/bin/ffuf /usr/local/bin/ffuf

- name: Install Gobuster
  tags: gobuster
  hosts: all
  tasks:
  - name: Download gobuster
    shell: |
      /usr/local/go/bin/go get github.com/OJ/gobuster

  - name: Setup gobuster
    become: yes
    shell: |
      mv go/bin/gobuster /usr/local/bin/gobuster

- name: Install Wfuzz
  tags: wfuzz
  hosts: all
  tasks:
    - name: Install Wfuzz
      become: yes
      command: pip3 install wfuzz

- name: Install Arjun
  tags: arjun
  hosts: all
  become: yes
  tasks:
  - name: Download and Setup Arjun
    shell: |
      git clone https://github.com/s0md3v/Arjun.git 
      cd Arjun && python3 setup.py install

  - name: Delete Arjun
    command: rm -rf Arjun