---
- name: Install dirsearch
  hosts: all
  tags: dirsearch
  tasks:
  - name: Download dirsearch
    command: git clone https://github.com/maurosoria/dirsearch.git
    
  - name: Setup dirsearch
    command: mv dirsearch /opt/crew/fuzzers/

  - name: Symlink dirsearch
    become: yes
    file:
      src: /opt/crew/fuzzers/dirsearch/dirsearch.py
      dest: /usr/local/bin/dirsearch  
      state: link

- name: Install Dirbuster
  hosts: all
  tags: dirbuster
  tasks:
  - name: Install dirbuster
    become: yes
    apt:
      pkg:
      - dirb

- name: Install sqlmap
  tags: sqlmap
  hosts: all
  tasks:
  - name: Download sqlmap
    command: git clone https://github.com/sqlmapproject/sqlmap.git /opt/crew/fuzzers/sqlmap/

  - name: Setup sqlmap
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/fuzzers/sqlmap/sqlmap.py "$@"

      dest:
        /usr/local/bin/sqlmap

  - name: Setup sqlmap as executable
    become: yes
    file: dest=/usr/local/bin/sqlmap mode=a+x
      
- name: Install FFuF
  tags: ffuf
  hosts: all
  tasks:
  - name: Download ffuf
    command: /usr/local/go/bin/go get -u github.com/ffuf/ffuf

  - name: Setup ffuf
    shell: |
      mkdir /opt/crew/fuzzers/ffuf
      mv go/bin/ffuf /opt/crew/fuzzers/ffuf

  - name: Symlink ffuf
    become: yes
    file:
      src: /opt/crew/fuzzers/ffuf/ffuf
      dest: /usr/local/bin/ffuf
      state: link

- name: Install Gobuster
  tags: gobuster
  hosts: all
  tasks:
  - name: Download gobuster
    shell: |
      /usr/local/go/bin/go get github.com/OJ/gobuster

  - name: Setup gobuster
    become: yes
    shell: |
      mkdir /opt/crew/fuzzers/gobuster
      mv go/bin/gobuster /opt/crew/fuzzers/gobuster/

  - name: Symink gobuster
    become: yes
    file:
      src: /opt/crew/fuzzers/gobuster/gobuster
      dest: /usr/local/bin/gobuster
      state: link

- name: Install Wfuzz
  tags: wfuzz
  hosts: all
  tasks:
    - name: Install Wfuzz
      become: yes
      command: pip3 install wfuzz

- name: Install Arjun
  tags: arjun
  hosts: all
  tasks:
  - name: Download
    command: git clone https://github.com/s0md3v/Arjun.git 
    
  - name: Setup Arjun
    become: yes
    shell: |
      cd Arjun
      python3 setup.py install
    
  - name: Delete Arjun
    become: yes
    command: rm -rf Arjun

- name: Install XSStrike
  tags: xsstrike
  hosts: all
  tasks:
  - name: Download XSStrike
    command: git clone https://github.com/s0md3v/XSStrike.git
  
  - name: Install XSStrike
    shell: |
      pip3 install -r XSStrike/requirements.txt
      mv XSStrike /opt/crew/fuzzers/
  
  - name: Setup XSStrike script
    become: yes
    copy:
      content: |
        #!/bin/bash
        python3 /opt/crew/fuzzers/XSStrike/xsstrike.py "$@"

      dest:
        /usr/local/bin/xsstrike
  
  - name: Setup XSStrike as executable
    become: yes
    file: dest=/usr/local/bin/xsstrike mode=a+x
  
  - name: Delete XSStrike
    command: rm -rf XSStrike