- name: Install Meg
  tags: meg
  hosts: all
  tasks:
  - name: Download meg
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/meg

  - name: Setup meg
    shell: |
      mkdir /opt/crew/misc/meg
      mv go/bin/meg /opt/crew/misc/meg/

  - name: Symink meg
    become: yes
    file:
      src: /opt/crew/misc/meg/meg
      dest: /usr/local/bin/meg
      state: link

- name: Install gf
  tags: gf
  hosts: all
  tasks:
  - name: Download gf
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/gf

  - name: Setup gf
    shell: |
      mkdir /opt/crew/misc/gf
      mv go/bin/gf /opt/crew/misc/gf/

  - name: Symink gf
    become: yes
    file:
      src: /opt/crew/misc/gf/gf
      dest: /usr/local/bin/gf
      state: link
