- name: Install Meg
  tags: meg
  hosts: all
  tasks:
  - name: Download meg
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/meg

  - name: Setup meg
    become: yes
    shell: |
      mv go/bin/meg /usr/local/bin/meg

