---
- name: Install lazyrecon
  hosts: all
  tasks:
  - name: Download lazyrecon
    become: yes
    shell: |
      git clone https://github.com/nahamsec/lazyrecon.git
      mv lazyrecon /opt/crew/recon/lazyrecon

  - name: Setup lazyrecon
    become: yes
    file:
      src: /opt/crew/recon/lazyrecon/lazyrecon.sh
      dest: /usr/local/bin/lazyrecon
      state: link

- name: Install Knockpy
  tags: knockpy
  hosts: all
  tasks:
  - name: Download and install Knockpy
    become: yes
    shell: |
      apt install python-dnspython
      git clone https://github.com/guelfoweb/knock.git
      cd knock
      python setup.py install

- name: Install Sublist3r
  tags: sublister
  hosts: all
  tasks:
  - name: Download and install Sublist3r
    become: yes
    shell: |
      git clone https://github.com/aboul3la/Sublist3r.git
      cd Sublist3r
      python3 setup.py install

- name: Install waybackurls
  tags: waybackurls
  hosts: all
  tasks:
  - name: Download waybackurls
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/waybackurls

  - name: Setup waybackurls
    become: yes
    shell: |
      mv go/bin/waybackurls /usr/local/bin/

- name: Install aquatone
  tags: aquatone
  hosts: all
  tasks:
  - name: Download aquatone
    shell: |
      /usr/local/go/bin/go get -u github.com/michenriksen/aquatone

  - name: Setup aquatone
    become: yes
    shell: |
      mv go/bin/aquatone /usr/local/bin/aquatone

- name: Install virtual-host-discovery
  tags: vhd
  hosts: all
  tasks:
  - name: Download vhd
    become: yes
    shell: |
      git clone https://github.com/jobertabma/virtual-host-discovery.git
      mv virtual-host-discovery /opt/crew/recon/virtual-host-discovery

  - name: Setup vhd
    become: yes
    copy:
      content: |
        #!/bin/bash 
        ruby /opt/crew/recon/virtual-host-discovery/scan.rb

      dest:
        /usr/local/bin/virtual-host-discovery

  - name: Setup vhd as executable
    become: yes
    file: dest=/usr/local/bin/virtual-host-discovery mode=a+x
      

- name: Install asnlookup
  tags: asnlookup
  hosts: all
  tasks:
  - name: Download asnlookup
    become: yes
    shell: |
      git clone https://github.com/yassineaboukir/asnlookup.git
      pip3 install -r asnlookup/requirements.txt
      mv asnlookup /opt/crew/recon/asnlookup

  - name: Setup asnlookup
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/recon/asnlookup/asnlookup.py

      dest:
        /usr/local/bin/asnlookup

  - name: Setup vhd as executable
    become: yes
    file: dest=/usr/local/bin/asnlookup mode=a+x


- name: Install MassDNS
  tags: massdns
  hosts: all
  tasks:
  - name: Download massdns
    shell: |
      git clone https://github.com/blechschmidt/massdns.git
      cd massdns && make
  - name: Setup massdns
    become: yes
    shell: |
      mv massdns/bin/massdns /usr/local/bin
      rm -rf massdns