---
- name: Install lazyrecon
  hosts: all
  tasks:
  - name: Download lazyrecon
    become: yes
    shell: |
      git clone https://github.com/nahamsec/lazyrecon.git
      mv lazyrecon /opt/crew/recon/lazyrecon

  - name: Setup lazyrecon
    become: yes
    file:
      src: /opt/crew/recon/lazyrecon/lazyrecon.sh
      dest: /usr/local/bin/lazyrecon
      state: link

- name: Install Knockpy
  tags: knockpy
  hosts: all
  tasks:
  - name: Download and install Knockpy
    become: yes
    shell: |
      apt install python-dnspython
      git clone https://github.com/guelfoweb/knock.git
      cd knock
      python setup.py install

- name: Install Sublist3r
  tags: sublister
  hosts: all
  tasks:
  - name: Download and install Sublist3r
    become: yes
    shell: |
      git clone https://github.com/aboul3la/Sublist3r.git
      cd Sublist3r
      python3 setup.py install

- name: Install waybackurls
  tags: waybackurls
  hosts: all
  tasks:
  - name: Download waybackurls
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/waybackurls

  - name: Setup waybackurls
    become: yes
    shell: |
      mv go/bin/waybackurls /usr/local/bin/