---
- name: Install lazyrecon
  hosts: all
  tags: lazyrecon
  tasks:
  - name: Download lazyrecon
    shell: |
      git clone https://github.com/nahamsec/lazyrecon.git
      mv lazyrecon /opt/crew/recon/lazyrecon

  - name: Setup lazyrecon
    become: yes
    file:
      src: /opt/crew/recon/lazyrecon/lazyrecon.sh
      dest: /usr/local/bin/lazyrecon
      state: link

- name: Install waybackurls
  tags: waybackurls
  hosts: all
  tasks:
  - name: Download waybackurls
    shell: |
      /usr/local/go/bin/go get -u github.com/tomnomnom/waybackurls

  - name: Setup waybackurls
    shell: |
      mkdir /opt/crew/recon/waybackurls
      mv go/bin/waybackurls /opt/crew/recon/waybackurls/
  
  - name: Symlink waybackurls
    become: yes
    file:
      src: /opt/crew/recon/waybackurls/waybackurls
      dest: /usr/local/bin/waybackurls
      state: link

- name: Install aquatone
  tags: aquatone
  hosts: all
  vars: 
    aquatone_ver: 1.7.0
  tasks:
  - name: Download aquatone
    command: wget https://github.com/michenriksen/aquatone/releases/download/v{{ aquatone_ver }}/aquatone_linux_amd64_{{ aquatone_ver }}.zip

  - name: Setup aquatone
    shell: |
      mkdir /opt/crew/recon/aquatone
      unzip -p aquatone_linux_amd64_{{ aquatone_ver }}.zip aquatone > /opt/crew/recon/aquatone/aquatone
      chmod u+x /opt/crew/recon/aquatone/aquatone
  
  - name: Symlink aquatone
    become: yes
    file:  
      src: /opt/crew/recon/aquatone/aquatone
      dest: /usr/local/bin/aquatone
      state: link

- name: Install virtual-host-discovery
  tags: vhd
  hosts: all
  tasks:
  - name: Download vhd
    shell: |
      git clone https://github.com/jobertabma/virtual-host-discovery.git
      mv virtual-host-discovery /opt/crew/recon/virtual-host-discovery

  - name: Setup vhd
    become: yes
    copy:
      content: |
        #!/bin/bash 
        ruby /opt/crew/recon/virtual-host-discovery/scan.rb "$@"

      dest:
        /usr/local/bin/virtual-host-discovery

  - name: Setup vhd as executable
    become: yes
    file: dest=/usr/local/bin/virtual-host-discovery mode=a+x
      
- name: Install asnlookup
  tags: asnlookup
  hosts: all
  tasks:
  - name: Download asnlookup
    command: git clone https://github.com/yassineaboukir/asnlookup.git
      
  - name: Install asnlookup
    become: yes
    shell: |
      pip3 install -r asnlookup/requirements.txt
      mv asnlookup /opt/crew/recon/

  - name: Setup asnlookup
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/recon/asnlookup/asnlookup.py "$@"

      dest:
        /usr/local/bin/asnlookup

  - name: Setup asnlookup as executable
    become: yes
    file: dest=/usr/local/bin/asnlookup mode=a+x

  - name: Delete asnlookup
    command: rm -rf asnlookup

- name: Install MassDNS
  tags: massdns
  hosts: all
  tasks:
  - name: Download massdns
    shell: |
      git clone https://github.com/blechschmidt/massdns.git
      cd massdns && make
  
  - name: Setup massdns
    shell: |
      mkdir /opt/crew/recon/massdns
      mv massdns/bin/massdns /opt/crew/recon/massdns/
  
  - name: Symlink massdns
    become: yes
    file:
      src: /opt/crew/recon/massdns/massdns
      dest: /usr/local/bin/massdns
      state: link
      
  - name: Delete massdns
    command: rm -rf massdns
      
- name: Install subfinder
  tags: subfinder
  hosts: all
  tasks:
  - name: Download subfinder
    command: /usr/local/go/bin/go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder

  - name: Setup subfinder
    shell: |
      mkdir /opt/crew/recon/subfinder
      mv go/bin/subfinder /opt/crew/recon/subfinder/
  
  - name: Symlink subfinder
    become: yes
    file:
      src: /opt/crew/recon/subfinder/subfinder
      dest: /usr/local/bin/subfinder
      state: link

- name: Install OWASP Amass
  tags: amass
  hosts: all
  vars:
    amass_ver: 3.11.5
  tasks:
    - name: Download Amass
      command: wget "https://github.com/OWASP/Amass/releases/download/v{{amass_ver}}/amass_linux_amd64.zip"
    
    - name: Extract Amass
      command: unzip amass_linux_amd64.zip
    
    - name: Setup Amass
      shell: |
        mkdir /opt/crew/recon/amass
        mv amass_linux_amd64/amass /opt/crew/recon/amass/
      
    - name: Symlink Amass
      become: yes
      file:
        src: /opt/crew/recon/amass/amass
        dest: /usr/local/bin/amass
        state: link
          
- name: Install hakrawler
  tags: hakrawler
  hosts: all
  tasks:
  - name: Download hakrawler
    shell: |
      /usr/local/go/bin/go get -v github.com/hakluke/hakrawler

  - name: Setup hakrawler
    become: yes
    shell: |
      mkdir /opt/crew/recon/hakrawler
      mv go/bin/hakrawler /opt/crew/recon/hakrawler
  
  - name: Symlink hakrawler
    become: yes
    file:
      src: /opt/crew/recon/hakrawler/hakrawler
      dest: /usr/local/bin/hakrawler
      state: link 

- name: Install recursebuster
  tags: recursebuster
  hosts: all
  tasks:
  - name: Download recursebuster
    command:  /usr/local/go/bin/go get -u github.com/c-sto/recursebuster

  - name: Setup recursebuster
    become: yes
    shell: |
      mkdir /opt/crew/recon/recursebuster
      mv go/bin/recursebuster /opt/crew/recon/recursebuster/

  - name: Symlink recursebuster
    become: yes
    file:
      src: /opt/crew/recon/recursebuster/recursebuster
      dest: /usr/local/bin/recursebuster
      state: link   

- name: Install findomain
  hosts: all
  tasks:
  - name: Download findomain
    command: wget https://github.com/Edu4rdSHL/findomain/releases/latest/download/findomain-linux -O findomain

  - name: Setup findomain
    become: yes
    shell: |
      mkdir /opt/crew/recon/findomain
      mv findomain /opt/crew/recon/findomain/findomain
      chmod +x /opt/crew/recon/findomain/findomain
      
  - name: Symlink findomain
    become: yes
    file:
      src: /opt/crew/recon/findomain/findomain
      dest: /usr/local/bin/findomain
      state: link   

- name: Install gau
  tags: gau
  hosts: all
  tasks:
  - name: Download gau
    shell: |
      /usr/local/go/bin/go get -u github.com/lc/gau

  - name: Setup gau
    shell: |
      mkdir /opt/crew/recon/gau
      mv go/bin/gau /opt/crew/recon/gau/
  
  - name: Symlink gau
    become: yes
    file:
      src: /opt/crew/recon/gau/gau
      dest: /usr/local/bin/gau
      state: link
  
- name: Install LinkFinder
  hosts: all
  tags: linkfinder
  tasks:
  - name: Download LinkFinder
    command: git clone https://github.com/GerbenJavado/LinkFinder.git
    
  - name: Install LinkFinder
    shell: |
      pip3 install -r LinkFinder/requirements.txt
      mv LinkFinder /opt/crew/recon/

  - name: Setup LinkFinder
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/recon/LinkFinder/linkfinder.py "$@"

      dest:
        /usr/local/bin/linkfinder
  
  - name: Setup LinkFinder as executable
    become: yes
    file: dest=/usr/local/bin/linkfinder mode=a+x

  - name: Delete LinkFinder
    command: rm -rf LinkFinder

- name: Install Striker
  tags: striker
  hosts: all
  tasks:
  - name: Download Striker
    command: git clone https://github.com/s0md3v/Striker.git
  
  - name: Install Striker
    shell: |
      pip3 install -r Striker/requirements.txt
      mv Striker /opt/crew/scanners/
  
  - name: Setup Striker script
    become: yes
    copy:
      content: |
        #!/bin/bash
        python3 /opt/crew/scanners/Striker/striker.py "$@"

      dest:
        /usr/local/bin/striker
  
  - name: Setup Striker as executable
    become: yes
    file: dest=/usr/local/bin/striker mode=a+x
  
  - name: Delete Striker
    command: rm -rf Striker

- name: Install dnsrecon
  tags: dnsrecon
  hosts: all
  tasks: 
  - name: Download dnsrecon
    command: git clone https://github.com/darkoperator/dnsrecon.git
  
  - name: Install dnsrecon
    become: yes
    command: pip3 install -r dnsrecon/requirements.txt

  - name: Setup dnsrecon
    command: mv dnsrecon /opt/crew/enum/
  
  - name: Setup dnsrecon script
    become: yes
    copy:
      content: |
        #!/bin/bash 
        python3 /opt/crew/enum/dnsrecon/dnsrecon.py "$@"

      dest:
        /usr/local/bin/dnsrecon
  
  - name: Setup dnsrecon as executable
    become: yes
    file: dest=/usr/local/bin/dnsrecon mode=a+x
  
  - name: Delete dnsrecon
    command: rm -rf dnsrecon