---
- name: Install nmap scanner 
  hosts: all
  become: yes
  tasks:
  - name: Install nmap    
    apt:
      pkg:
      - nmap

- name: Install zmap scanner
  hosts: all
  tags: zmap
  become: yes
  tasks:
  - name: Install zmap
    apt:
      pkg:
      - zmap
  - name: Setup zmap
    command: mv /usr/sbin/zmap /usr/local/bin/zmap

- name: Install nuclei 
  hosts: all
  tags: nuclei
  tasks:
  - name: Download nuclei
    shell: |
      git clone https://github.com/projectdiscovery/nuclei.git
      cd nuclei/v2/cmd/nuclei
      /usr/local/go/bin/go build
      /usr/local/go/bin/go mod tidy

  - name: Setup nuclei
    shell: |
      mkdir /opt/crew/scanners/nuclei
      mv nuclei/v2/cmd/nuclei/nuclei /opt/crew/scanners/nuclei/
  
  - name: Symlink nuclei
    become: yes  
    file:
      src: /opt/crew/scanners/nuclei/nuclei
      dest: /usr/local/bin/nuclei
      state: link
      
  - name: Update nuclei templates
    command: nuclei -update-templates

  - name: Delete nuclei
    command: rm -rf nuclei/

- name: Install Masscan 
  hosts: all
  tags: masscan
  tasks:
  - name: Download masscan
    shell: |
      git clone https://github.com/robertdavidgraham/masscan
      cd masscan 
      make

  - name: Setup masscan
    become: yes  
    shell: |
      cd masscan
      make install
  
  - name: Remove masscan
    command: rm -rf masscan

- name: Install nikto
  tags: nikto
  hosts: all
  tasks: 
  - name: Download nikto
    command: git clone https://github.com/sullo/nikto
  
  - name: Setup nikto
    shell: |
      mv nikto/program /opt/crew/scanners/nikto
  
  - name: Setup nikto script
    become: yes
    copy:
      content: |
        #!/bin/bash
        perl /opt/crew/scanners/nikto/nikto.pl "$@"

      dest:
        /usr/local/bin/nikto
  
  - name: Setup nitko as executable
    become: yes
    file: dest=/usr/local/bin/nikto mode=a+x
  
  - name: Delete nikto
    command: rm -rf nikto