---
- name: Install nmap scanner 
  hosts: all
  become: yes
  tasks:
  - name: Install nmap    
    apt:
      pkg:
      - nmap

- name: Install zmap scanner
  hosts: all
  tags: zmap
  become: yes
  tasks:
  - name: Install zmap
    apt:
      pkg:
      - zmap
  - name: Setup zmap
    command: mv /usr/sbin/zmap /usr/local/bin/zmap

- name: Install Nuclei 
  hosts: all
  tags: nuclei
  tasks:
  - name: Download nuclei
    shell: |
      git clone https://github.com/projectdiscovery/nuclei.git
      cd nuclei/v2/cmd/nuclei
      go build

  - name: Setup nuclei
    become: yes  
    command: mv nuclei/v2/cmd/nuclei/nuclei /usr/local/bin

  - name: Update nuclei templates
    command: nuclei -update-templates